import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Temporary placeholder Firebase configuration. Replace every value in this
/// file with the real configuration generated by the Firebase CLI (`flutterfire
/// configure`) when wiring the app to your project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO_WEB_API_KEY',
    appId: '1:000000000000:web:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'todo-project-id',
    authDomain: 'todo-project-id.firebaseapp.com',
    databaseURL: 'https://todo-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'todo-project-id.appspot.com',
    measurementId: 'G-TODO12345',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO_ANDROID_API_KEY',
    appId: '1:000000000000:android:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'todo-project-id',
    databaseURL: 'https://todo-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'todo-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO_IOS_API_KEY',
    appId: '1:000000000000:ios:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'todo-project-id',
    databaseURL: 'https://todo-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'todo-project-id.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO_MACOS_API_KEY',
    appId: '1:000000000000:macos:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'todo-project-id',
    databaseURL: 'https://todo-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'todo-project-id.appspot.com',
    iosBundleId: 'com.example.todo.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSJiL23yUzqWL5btwIfxmLFurF8HIklYk',
    appId: '1:714453411024:web:519f0d64c9719ba62e2ad5',
    messagingSenderId: '714453411024',
    projectId: 'real-estate-application-agent',
    authDomain: 'real-estate-application-agent.firebaseapp.com',
    storageBucket: 'real-estate-application-agent.firebasestorage.app',
    measurementId: 'G-Q79NF6BZQW',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'TODO_LINUX_API_KEY',
    appId: '1:000000000000:linux:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'todo-project-id',
    databaseURL: 'https://todo-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'todo-project-id.appspot.com',
  );
}
